# globals.py
from pathlib import Path
import polars as pl
from typing import Dict, List
import polars as pl
from pathlib import Path
from typing import Dict, List, Optional, Any

ROOT_DATA_PATH = Path(
    r"D:\caarteaga\Documents\Departamento de IA\Trabajos\SIGER Documentos\entrega_siger")

TABLES_TO_PROCESS = [
    # 'CTSOCIOS',
    'MVCARATULAS', 'CFVARIABLES', 'CTSOCIOS', 'MVVARACTO',
    # 'MVFRMACTO', 'CTMUNICIPIOS', 'MVSOLICITUDES', 'BTSOLICITUDES', 'CTESTADOSACTO',
    # 'CTUSUARIOS_202511281728', 'CTGIROS', 'CTOFICINAS', 'PAGO_PORTAL', 'CTTIPOSOCIEDAD'
]

# Tables with '"' inside the cells
quote_char_double_quotes = ['MVCARATULAS', 'MVFRMACTO', 'MVSOLICITUDES',
                            'CTUSUARIOS_202511281728', 'PAGO_PORTAL']

# Columns to be dropped
col_drop = ['CRFME', 'DSANTREG', 'FCCONSTITUCION', 'CFPAGODERECHOS_LLOFICINA',
            'FCNACIMIENTO', 'FCMODIFICACION', 'DSDOMICILIO', 'NOMONTO', 'BLFOTO',
            'LLESTDOACTOPRE', 'DSACTO', 'NOCONSECUTIVO', 'DSNOMBRERESPOFIC',
            'LLMVFRMACTOSUB', 'FCINGRESO', 'FCINSCRIPCION', 'LLGRUPOTRABAJO',
            'NOCONTINUIDAD', 'DSOBSERVACIONES', 'LLENTREGA', 'LLTIPOACLARACION',
            'LLPAGOSSINREG', 'LLSOLINSCRIPCION', 'LLSOLICITUD_2', 'LLPAGOSSRPETUSU',
            'FCLIMITESUBS', 'DSTELEFONO', 'DSFEA', 'DSMIMETYPEFOTO', 'FCREACTIVACION',
            'CRCODCONFIRMACION', 'BOESFEDATARIO', 'LLFEDATARIO', 'DSJUSTIFICACION',
            'FCACTUALIZCONTRAS', 'FCULTINTLOGIN', 'DSEXTENCION', 'FCINIOPERACION',
            'DSPAGINAWEB', 'LLPROCESO', 'FCALTA', 'DSREFERENCIARQ', 'NOTXCOUNTRQ',
            'DSCONCEPTORQ', 'DSRFCRQ', 'DSCLAVEMUNICIPIORQ', 'NOMOVIMIENTOSRQ',
            'DSACTORQ', 'DSDOMICILIORQ', 'DSENTIDADRQ', 'DSMUNICIPIORQ', 'DSCURP',
            'DSCPRQ', 'DSTELEFONORQ', 'DSIDNOTARIORQ', 'DSNOMBRENOTARIORQ', 'FCLIMITE',
            'DSRFCNOTARIORQ', 'DSTXIDRQ', 'DSNOMBRENOTARIORQ', 'DSFEDANETRQ',
            'DSTELEFONONOTARIORQ', 'DSMAILNOTARIORQ', 'DSCUENTARQ', 'DSPASSWORDRQ',
            'NOSERVICIOIDRQ', 'DSNOMBRERQ', 'DSAPELLIDOPATERNORQ', 'DSAPELLIDOMATERNORQ',
            'DSRAZONSOCIALRQ', 'DSTRAMITERQ', 'NOTXCOUNTRS', 'DSTIPOPAGORS',
            'DSCONCEPTORS', 'DSNOTARIORS', 'DSFOLIORS', 'FCTRANSACCIONRS']

# Columns 'Int32' type for all tables
col_int32 = ['LLCARATULA', 'LLOFICINA', 'LLMUNICIPIO', 'LLSOCIO', 'LLESTADO',
             'LLGIRO', 'LLTIPOSOCIEDAD', 'LLVARIABLE', 'LLNACIONALIDAD',
             'LLESTATUSCARATULA', 'LLPAGODERECHO', 'LLMVFRMACTO', 'LLSOLFRMPRE',
             'LLESTDOACTO', 'LLFORMAACTO', 'LLVARACTO', 'LLTIPOSOLICITUD',
             'LLETAPA', 'LLCOMPFEDA', 'LLUSUARIO', 'LLSOLICITUD', 'LLPAGO',
             'LLESTATUSBANDEJA', 'LLESTATUS', 'LLUSOHORARIO', 'LLOFICINAMG']

# Columns 'Int8' type for all tables
col_int8 = ['BOMORAL', 'BOACERVO', 'BOACTIVO', 'BOVARIABLERANGO', 'BOANOTACIONACTIVA',
            'BOMIGRACION', 'BOINGRESO', 'BOINCIDENCIAS']

# Columns 'DATE' type for all tables
col_date = ['FCAPERTURA', 'FCNACIMIENTO', 'FCCONSTITUCION', 'FCMODIFICACION',
            'FCINGRESO', 'FCINSCRIPCION', 'FULTLOGIN', 'FCALTA', 'FCTRANSACCIONRS']

# String Columns to be converted to string, to be clean and to be converted to uppercase
col_str = ['DSDENSOCIAL', 'DSDIRECCION', 'DSDURACION', 'DSNOMBRESOCIO', 'DSRFC',
           'DSGIRO', 'DSTIPOSOCIEDAD', 'DSOBJETO', 'DSAPELLIDOPATERNO', 'DSESTADO',
           'DSNACIONALIDAD', 'DSAPELLIDOMATERNO', 'DSNOMBREVARIABLE', 'DSCODIGO',
           'DSDESCRIPCION', 'DSNOMBRE', 'DSOFICINA', 'DSMUNICIPIO']
